-- ============================================================
-- SKILLS GET A CATEGORY, AND A GREATLY WIDER CATALOGUE
--
-- The grouping already existed -- as comments in migration 016. Nothing
-- could read a comment, so every screen that offers skills invented its own
-- answer: the project wizard hard-coded nine of them, onboarding showed the
-- first thirty alphabetically, and settings rendered all seventy as one wall
-- of chips. A category column lets all three show the same grouped list.
--
-- The catalogue roughly doubles, and software is a first-class group rather
-- than ten names tacked on the end -- Canva, Figma, CapCut and the rest are
-- what people actually search for.
--
--   CATEGORY               N
--   Photography           35
--   Videography           29
--   On set & production   30
--   Editing & post        41
--   Software & tools      45
--   TOTAL                180
--
-- Idempotent: ON CONFLICT updates the category, so re-running is safe and so
-- is running it over the 016 seed. Skills typed by users that are not in this
-- list keep a null category and show under "Other" -- they are not deleted.
--
-- Run AFTER 026_brand_rename.sql.
-- ============================================================

begin;

alter table public.skills add column if not exists category text;

insert into public.skills (name, category) values
  ('Wedding Photography', 'photography'),
  ('Event Photography', 'photography'),
  ('Portrait Photography', 'photography'),
  ('Product Photography', 'photography'),
  ('Fashion Photography', 'photography'),
  ('Food Photography', 'photography'),
  ('Real Estate Photography', 'photography'),
  ('Architectural Photography', 'photography'),
  ('Travel Photography', 'photography'),
  ('Sports Photography', 'photography'),
  ('Newborn Photography', 'photography'),
  ('Maternity Photography', 'photography'),
  ('Corporate Headshots', 'photography'),
  ('Jewellery Photography', 'photography'),
  ('Automotive Photography', 'photography'),
  ('Concert Photography', 'photography'),
  ('Documentary Photography', 'photography'),
  ('Street Photography', 'photography'),
  ('Family Photography', 'photography'),
  ('Pet Photography', 'photography'),
  ('Editorial Photography', 'photography'),
  ('Lifestyle Photography', 'photography'),
  ('Interior Photography', 'photography'),
  ('Macro Photography', 'photography'),
  ('Wildlife Photography', 'photography'),
  ('Astrophotography', 'photography'),
  ('Fine Art Photography', 'photography'),
  ('Boudoir Photography', 'photography'),
  ('Graduation Photography', 'photography'),
  ('Stock Photography', 'photography'),
  ('360 & Virtual Tours', 'photography'),
  ('Flat Lay Photography', 'photography'),
  ('Catalogue Photography', 'photography'),
  ('Pre-Wedding Shoots', 'photography'),
  ('Festival & Cultural Shoots', 'photography'),
  ('Wedding Videography', 'videography'),
  ('Event Videography', 'videography'),
  ('Corporate Video', 'videography'),
  ('Commercial & Ad Films', 'videography'),
  ('Music Videos', 'videography'),
  ('Documentary Filmmaking', 'videography'),
  ('Real Estate Video', 'videography'),
  ('Product Video', 'videography'),
  ('Social Media Reels', 'videography'),
  ('YouTube Content', 'videography'),
  ('Livestream Production', 'videography'),
  ('Interview Filming', 'videography'),
  ('Short Films', 'videography'),
  ('Explainer Videos', 'videography'),
  ('Training & E-Learning Video', 'videography'),
  ('Podcast Video', 'videography'),
  ('Property Walkthroughs', 'videography'),
  ('Fashion Film', 'videography'),
  ('Sports Videography', 'videography'),
  ('Aerial Cinematography', 'videography'),
  ('Time-Lapse', 'videography'),
  ('Hyperlapse', 'videography'),
  ('Green Screen Shoots', 'videography'),
  ('Talking Head Video', 'videography'),
  ('Testimonial Video', 'videography'),
  ('Crowdfunding Video', 'videography'),
  ('Brand Films', 'videography'),
  ('Behind-the-Scenes Video', 'videography'),
  ('Recipe & Food Video', 'videography'),
  ('Cinematography', 'production'),
  ('Camera Operation', 'production'),
  ('Lighting', 'production'),
  ('Gimbal Operation', 'production'),
  ('Drone & Aerial', 'production'),
  ('Multi-Cam Setup', 'production'),
  ('Sound Recording', 'production'),
  ('Studio Setup', 'production'),
  ('Directing', 'production'),
  ('Storyboarding', 'production'),
  ('Production Assistance', 'production'),
  ('Second Shooter', 'production'),
  ('Assistant Camera', 'production'),
  ('Focus Pulling', 'production'),
  ('Steadicam', 'production'),
  ('Jib & Crane Operation', 'production'),
  ('Grip & Rigging', 'production'),
  ('Boom Operation', 'production'),
  ('Lavalier Mic Setup', 'production'),
  ('Teleprompter Operation', 'production'),
  ('Data Wrangling', 'production'),
  ('Location Scouting', 'production'),
  ('Set Design', 'production'),
  ('Prop Styling', 'production'),
  ('Hair & Makeup Coordination', 'production'),
  ('Wardrobe Styling', 'production'),
  ('Casting', 'production'),
  ('Permits & Logistics', 'production'),
  ('Call Sheets & Scheduling', 'production'),
  ('Script Writing', 'production'),
  ('Video Editing', 'editing'),
  ('Photo Retouching', 'editing'),
  ('Colour Grading', 'editing'),
  ('Colour Correction', 'editing'),
  ('Motion Graphics', 'editing'),
  ('2D Animation', 'editing'),
  ('3D Animation', 'editing'),
  ('VFX & Compositing', 'editing'),
  ('Subtitling', 'editing'),
  ('Audio Post-Production', 'editing'),
  ('Album Design', 'editing'),
  ('Photo Culling', 'editing'),
  ('Reels & Shorts Editing', 'editing'),
  ('Podcast Editing', 'editing'),
  ('Multicam Editing', 'editing'),
  ('Sound Design', 'editing'),
  ('Audio Mixing', 'editing'),
  ('Noise Reduction', 'editing'),
  ('Skin Retouching', 'editing'),
  ('Beauty Retouching', 'editing'),
  ('Product Retouching', 'editing'),
  ('Background Removal', 'editing'),
  ('Object Removal', 'editing'),
  ('Sky Replacement', 'editing'),
  ('Composite Editing', 'editing'),
  ('Photo Restoration', 'editing'),
  ('Colourisation', 'editing'),
  ('Thumbnail Design', 'editing'),
  ('Title Design', 'editing'),
  ('Lower Thirds', 'editing'),
  ('Captions & Subtitles', 'editing'),
  ('LUT Creation', 'editing'),
  ('Proxy Workflow', 'editing'),
  ('Batch Editing', 'editing'),
  ('Image Masking', 'editing'),
  ('Clipping Path', 'editing'),
  ('Green Screen Keying', 'editing'),
  ('Rotoscoping', 'editing'),
  ('Motion Tracking', 'editing'),
  ('Speed Ramping', 'editing'),
  ('Transitions & Effects', 'editing'),
  ('Adobe Premiere Pro', 'software'),
  ('Final Cut Pro', 'software'),
  ('DaVinci Resolve', 'software'),
  ('Adobe After Effects', 'software'),
  ('Adobe Photoshop', 'software'),
  ('Adobe Lightroom', 'software'),
  ('Capture One', 'software'),
  ('Blender', 'software'),
  ('Cinema 4D', 'software'),
  ('CapCut', 'software'),
  ('Canva', 'software'),
  ('Figma', 'software'),
  ('Adobe Illustrator', 'software'),
  ('Adobe InDesign', 'software'),
  ('Adobe Audition', 'software'),
  ('Adobe Express', 'software'),
  ('Adobe Bridge', 'software'),
  ('Lightroom Classic', 'software'),
  ('Affinity Photo', 'software'),
  ('Affinity Designer', 'software'),
  ('Avid Media Composer', 'software'),
  ('Nuke', 'software'),
  ('Mocha Pro', 'software'),
  ('Houdini', 'software'),
  ('Autodesk Maya', 'software'),
  ('Unreal Engine', 'software'),
  ('Audacity', 'software'),
  ('Logic Pro', 'software'),
  ('Pro Tools', 'software'),
  ('Descript', 'software'),
  ('Filmora', 'software'),
  ('iMovie', 'software'),
  ('VN Editor', 'software'),
  ('Topaz Photo AI', 'software'),
  ('Topaz Video AI', 'software'),
  ('Luminar Neo', 'software'),
  ('Photo Mechanic', 'software'),
  ('Narrative Select', 'software'),
  ('AfterShoot', 'software'),
  ('Imagen AI', 'software'),
  ('Frame.io', 'software'),
  ('Pixieset', 'software'),
  ('ShootProof', 'software'),
  ('Notion', 'software'),
  ('Trello', 'software')
on conflict (name) do update set category = excluded.category;

-- Anything a user added by hand before this ran.
update public.skills set category = null where category = '';

create index if not exists skills_category_idx on public.skills (category);

commit;
